# Anexo IV {.unnumbered}

$$M = \text{PMT}\cdot \text{FAcC}$$ {#eq-FAcC}

```{r, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, echo=FALSE, fig.pos="H", 
                      fig.path="./img-modelagem/",
                      fig.align = "center", dev = "png", dpi = 600, 
                      out.width = "80%", warning = FALSE, message = FALSE,
                      size = "small")
library(ggplot2)
library(ggthemes)
theme_set(theme_bw())
library(appraiseR)
library(knitr)
```

```{r}
FAcC <- function(i, t){
  ((1+i)^t-1)/i
}
```

```{r}
periods <- c(1:60, 90, 100, 120, 180, 240)
j <- c((1+2/100)^(1/12)-1, (1+3/100)^(1/12)-1, (1+4/100)^(1/12)-1, 
       (1+5/100)^(1/12)-1, 0.5/100, (1+8/100)^(1/12)-1, (1+9/100)^(1/12)-1,
       (1+10/100)^(1/12)-1, (1+11/100)^(1/12)-1, (1+12/100)^(1/12)-1)
```


```{r}
#| label: tbl-FAcC
#| tbl-cap: "Fator de Acumulação Composta (FAcC)."
n <- length(periods)
m <- length(j)
M <- matrix(nrow = n, ncol = m)
for (t in 1:n) {
  for (i in 1:m){
    M[t,i] <- FAcC(j[i], periods[t])
  }
}
facc <- as.data.frame(M)
facc <- cbind(periods, facc)
colnames(facc) <- c("T/i(%)", ".165%", ".247%", ".327%", ".407%", ".50%", 
                    ".64%", ".72%", ".80%", ".87%", ".95%")
rownames(facc) <- periods
facc |>
  kable(digits = 3, row.names =  F,
        format.args = list(decimal.mark = ",", big.mark = "."))
```

```{r}
#| label: tbl-FAcC2
#| tbl-cap: "Fator de Acumulação Composta (FAcC)."
M <- matrix(nrow = n, ncol = 10)
for (t in 1:n) {
  for (i in 1:10){
    M[t,i] <- FAcC(i/100, periods[t])
  }
}
facc <- as.data.frame(M)
colnames(facc) <- c("1%", "2%", "3%", "4%", "5%", "6%", "7%", "8%", "9%", "10%")
rownames(facc) <- periods
facc |>
  kable(digits = 3, row.names =  F,
        format.args = list(decimal.mark = ",", big.mark = "."))
```

```{r}
#| label: tbl-FAcC3
#| tbl-cap: "Fator de Acumulação Composta (FAcC)."
M <- matrix(nrow = n, ncol = 10)
for (t in 1:n) {
  for (i in 1:10){
    M[t,i] <- FAcC((10+i)/100, periods[t])
  }
}
facc <- as.data.frame(M)
colnames(facc) <- c("11%", "12%", "13%", "14%", "15%", "16%", "17%", "18%", 
                    "19%", "20%")
rownames(facc) <- periods
facc |>
  kable(digits = 3, row.names =  F,
        format.args = list(decimal.mark = ",", big.mark = "."))
```