# Anexo III {.unnumbered}


$$C = M\cdot \text{CPW}(i,T) = M\cdot \frac{i}{\ln(1 + i)} \frac{1}{(1+i)^T}$$ {#eq-PW}

```{r, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, echo=FALSE, fig.pos="H", 
                      fig.path="./img-modelagem/",
                      fig.align = "center", dev = "png", dpi = 600, 
                      out.width = "80%", warning = FALSE, message = FALSE,
                      size = "small")
library(ggplot2)
library(ggthemes)
theme_set(theme_bw())
library(appraiseR)
library(knitr)
```

```{r}
CPW <- function(i, t) {
  i/log(1+i)*1/(1+i)^t
}
```


```{r}
periods <- c(1:60, 90, 100, 120, 180, 240, 300, 360)
j <- c((1+2/100)^(1/12)-1, (1+3/100)^(1/12)-1, (1+4/100)^(1/12)-1, 
       (1+5/100)^(1/12)-1, 0.5/100, (1+8/100)^(1/12)-1, (1+9/100)^(1/12)-1,
       (1+10/100)^(1/12)-1, (1+11/100)^(1/12)-1, (1+12/100)^(1/12)-1)
```



```{r}
#| label: tbl-CPW1
#| tbl-cap: "Fator de Atualização Contínua do Capital (CPW)."
n <- length(periods)
m <- length(j)
M <- matrix(nrow = n, ncol = m)
for (t in 1:n) {
  for (i in 1:m){
    M[t,i] <- CPW(j[i], periods[t])
  }
}
cpw <- as.data.frame(M)
cpw <- cbind(periods, cpw)
colnames(cpw) <- c("T/i(%)", ".165%", ".247%", ".327%", ".407%", ".50%", ".64%",
                   ".72%", ".80%", ".87%", ".95%")
# rownames(fac) <- periods
cpw |>
  kable(digits = 4, row.names = F,
        format.args = list(decimal.mark = ",", big.mark = "."))
```

```{r}
#| label: tbl-CPW2
#| tbl-cap: "Fator de Atualização Contínua do Capital (CPW)."
M <- matrix(nrow = n, ncol = 10)
for (t in 1:n) {
  for (i in 1:10){
    M[t,i] <- CPW(i/100, periods[t])
  }
}
cpw <- as.data.frame(M)
cpw <- cbind(periods, cpw)
colnames(cpw) <- c("T/i(%)", "1%", "2%", "3%", "4%", "5%", "6%", "7%", "8%", 
                   "9%", "10%")
cpw |>
  kable(digits = 4, row.names = F,
        format.args = list(decimal.mark = ",", big.mark = "."))
```
